language: c

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    addons:
      apt:
        packages:
        - gcc
  - os: osx
    compiler: clang
    install:
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    addons:
      homebrew:
        update: false
    env:
      - ARCH=x64
      - CC_OVERRIDE=clang

script:
  - pwd
  - make
  - ./hello
  - echo "some text for a file" > tmp.txt
  - more tmp.txt
  - echo
  - tail tmp.txt
  - echo
  - cat tmp.txt
